import os
import subprocess

from oqd_heisenberg_ion.common.driver.base import Driver


class ExactDiagonalization(Driver):
    """
    Driver subclass for Exact Diagonalization.
    Calls the Julia ED engine via a python subprocess which uses the input file generated by the preprocessor to specify the simulation parameters
    """

    def __init__(self, simulation_folder, simulator_inputs):
        """
        constructor for the ED Driver subclass. Specifies the ED engine path, the ED engine input file path and the Julia path

        Args:
            simulation_folder (str): the parameter set simulation folder
            simulator_inputs (dict): contains the Julia path as a key value pair
        """

        super().__init__(simulation_folder)

        self.input_file = os.path.join(simulation_folder, "inputs.txt")
        self.julia_path = simulator_inputs["julia_path"]
        self.ed_engine = os.path.dirname(os.path.abspath(__file__)) + "/engine.jl"

    def simulate(self):
        """
        calls the Julia engine for the ED calculation

        Returns:
            (int): exit code, 0 if the program executes to completion
        """

        try:
            subprocess.run(
                [self.julia_path, self.ed_engine, self.input_file], check=True, capture_output=True, text=True
            )
        except subprocess.CalledProcessError as error:
            print(f"Julia execution failed with exit code: {error.returncode}\n")
            print(f"STDOUT: {error.stdout}")
            print(f"STDERR:{error.stderr}")
            raise

        return 0
